### ISSUE TITLE
Server thread/WARNING

### ISSUE THREAD

**Issue by BroCrows** [poggit-orphanage/GrabBag#17] opened 2019-05-15 21:50 UTC
When I start my server all of the plugins are loading up nicely but this one, it says [Server thread/WARNING] Plugin ‘GrabBag’ has registered a listener for
‘pocketmine\event\server\RemoteServerCommandEvent’ on method ‘aliuly\grabbag\CmdSelMgr->onConsleCmd’, but the event Deprecated.

**Comment by dktapps** [comment] 2019-05-16 07:13
duplicate of #12

**Closed as completed by dktapps** 2019-05-16 07:13 UTC
